os: osx
osx_image: xcode9.2
language: swift
install: swift package update
script:
- swift run builder run
notifications:
  email: false
  slack:
    rooms:
      secure: RcXwEtbidh0RjdBVapqNa6HVkVNnYqyPBsxnecl9I3fLVo3xdmgbjnj1ftWM/zfx/vHY3YcxB9bMQjLbMr0P4PLFGgSXcuuX1FlFSg2gGYx/N3k28M+Aiux3pTvfmTeK8Ik1Za0bugptE8muj2hNiFCCz3VC5jx/t1k0TfgzaKP7tkxzAkFaDSvAjbysgbcwbyodjuKu34jDO6IavNWHSxRiDYiDZFqXeCoRNldATpPGmcjUORygKGfcLqC3emzuf8ML2cywS/6Aq6CiwXWyXambzQq5QFAYbj3iqvw8qWhLOulpelL03/h35IGBBJs5ixOS6HSYTkXS+Ge5+65GAg7r9TEEMb9uJxZrmtleNDYtcEHEfMgz/LEuQtqIdwZ8Azic314cwgXBR5N/78CL22aXOScee7LV6Xd/AX6FrlzYXaf5J+MhK6gsTyYajt2dWfaJI9YaBneMkKCZI90SJV1vX8Fhvfba2bIZ5tgROzVqbbSIkblnixbeHV9tm3f/3o/pH2vm0yK0Vt1DQemcCZ31lQFh0n9bWD9wcA6T1elyvnPMKwFa7+/nHWubU83ys5ByET0GyDKT+53iQ+ztjPIX3VObnjITRZxFoEkdxiaiGfOJqLh3vr8LoD9G3Cd0BaACDVtSIbj2jzQ5EkDWaSsNAskvkkZfBqY0EPekMOA=
