os: osx
osx_image: xcode9.3
language: swift
sudo: required
install:
- wget https://swift.org/builds/swift-4.2-branch/xcode/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a-osx.pkg
- sudo installer -pkg swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a-osx.pkg -target /
- export PATH="/Library/Developer/Toolchains/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a.xctoolchain/usr/bin:$PATH"
- swift --version
- swift package update
script:
- swift run builder run
notifications:
  email: false
  slack:
    rooms:
      secure: Vm/7BsbDgrjHX5Y0VowraaryLRokdFFof8gzaxc3QmogOhnSOvn7a9pq3FdS7cx0vzo0q0XAMp3OHVtyVQS3KDiKo8Hl+QXWkqQZtUINYyZoN2JAfQYsURoBSW9XbPsT+MyqFZJPMr5Q4C5HgZcvRDOW+DmJi0mQgb8DfXtnCz3EmEadLOMvl6DISJA9gN4yxj7VfG1vA9cE5zeu4cW2iy+0jbpL4XIiAKFsNVeH+6Y1OGMwia18KpzLr+mwpPt15vCzPVlDuk1fTB+EEHVDfpuL9Ngi2BjVZWmExSkwt1cRriYPKm3+hAhFMM9gM4I9LAZt2sF2aL96uuxlPocq0UAUvV0/DQ1qBpgX6Y2RAJ5W5NDCZgATv/hl2CI47fmHwbsBK6UIE7ykGubxPwi0SKMEjjnpPAmUeqPGs6BIQ/j3XmXQyHe5CE9ZWQAeI1ZD1/qOzrq7RPMbSCzxnGs9k6lkVB6ZPIPG4uuIAMsAPda/REo1bdPYmMXipCWEUtKmeNlPXDoPnkAP3F9gOJWl1oP/F8o1bzpj8UmmWmOK4DeTsrEIC1WNs4c4OXv+DmxtGGB85nwfmq8H/nXKBLAgfeF/Xvv7H2Un7pUMN44NiSTMCr5fB3fXK4bInLBteVAz+Ke9ZQfi4HIEnsgS0B2ksFDvfofzbT4M/arm1xvOHeU=
